man(chaos).
man(erebus).
man(aether).
man(tartarus).
man(eros).
man(pontus).
man(uranus).
man(oceanus).
man(cronus).
man(coeus).
man(hyperion).
man(iapetuys).
man(hades).
man(poseidon).
man(zeus).
man(helios).
man(apollo).
man(atlas).
man(hermes).
man(prometheus).
man(epimetheus).
man(ares).
man(hephaetus).
man(dionysus).
woman(forehead).
woman(nyx).
woman(hemera).
woman(gaia).
woman(tethys).
woman(mnemosyne).
woman(rhea).
woman(themis).
woman(phoebe).
woman(theia).
woman(clymene).
woman(hestia).
woman(demeter).
woman(persephone).
woman(artemis).
woman(eos).
woman(selene).
woman(maia).
woman(dione).
woman(aphrodite).
woman(athena).
woman(hebe).
woman(hera).
woman(semelle).
woman(leto).
parent(chaos,erebus).
parent(nyx,erebus).
parent(erebus,aether).
parent(erebus,hemera).
parent(nyx,aether).
parent(nyx,hemera).
parent(aether,gaia).
parent(aether,tartarus).
parent(aether,eros).
parent(aether,pontus).
parent(hemera,gaia).
parent(hemera,tartarus).
parent(hemera,eros).
parent(hemera,pontus).
parent(uranus,oceanus).
parent(uranus,mnemosyne).
parent(uranus,cronus).
parent(uranus,themis).
parent(uranus,coeus).
parent(uranus,phoebe).
parent(uranus,hyperion).
parent(uranus,iapetuys).
parent(gaia,oceanus).
parent(gaia,mnemosyne).
parent(gaia,cronus).
parent(gaia,phoebe).
parent(gaia,themis).
parent(gaia,coeus).
parent(gaia,hyperion).
parent(gaia,iapetuys).
parent(cronus,hestia).
parent(cronus,hades).
parent(cronus,poseidon).
parent(cronus,zeus).
parent(cronus,hera).
parent(cronus,demeter).
parent(rhea,hestia).
parent(rhea,hades).
parent(rhea,poseidon).
parent(rhea,zeus).
parent(rhea,hera).
parent(rhea,demeter).
parent(zeus,athena).
parent(zeus,ares).
parent(zeus,hebe).
parent(zeus,hephaetus).
parent(zeus,dionysus).
parent(zeus,artemis).
parent(zeus,apollo).
parent(zeus,hermes).
parent(zeus,aphrodite).
parent(zeus,persephone).
parent(forehead,athena).
parent(hera,ares).
parent(hera,hephaetus).
parent(semelle,dionysus).
parent(demeter,persephone).
parent(coeus,leto).
parent(zeus,leto).
parent(leto,artemis).
parent(leto,apollo).
parent(hyperion,eos).
parent(hyperion,selene).
parent(hyperion,helios).
parent(theia,eos).
parent(theia,selene).
parent(theia,helios).
parent(iapetuys,atlas).
parent(iapetuys,prometheus).
parent(iapetuys,epimetheus).
parent(clymene,atlas).
parent(clymene,prometheus).
parent(clymene,atlas).
parent(atlas,maia).
parent(epimetheus,dione).
parent(maia,hermes).
parent(dione,aphrodite).
father(F,C):-man(F),parent(F,C).
mother(M,C):-woman(M),parent(M,C).
is_father(F):-father(F,_).
is_mother(M):-mother(M,_).
son(S,P):-man(S),parent(P,S).
daughter(D,P):-woman(D),parent(P,D).
siblings(A,B):-parent(P,A),parent(P,B),A\=B.
full_siblings(A,B):-parent(F,A),parent(F,B),parent(M,A),parent(M,B),A\=B,F\=M.
uncle(U,N):-man(U),siblings(U,P),parent(P,N).
aunt(A,N):-woman(A),siblings(A,P),parent(P,N).
grand_parent(G,N):-parent(G,X),parent(X,N).


